### ISSUE TITLE
pruning problem

### ISSUE THREAD

**Issue by eeric** [Syencil/mobile-yolov5-pruning-distillation#4]
training dataset: coco2017
model weights:  yolov5s.pt
classes = 80
why was lower to value of p or r  when pruning?

as following:
 Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
      3/49     2.66G   0.06193    0.0939   0.04484    0.2007       141       640: 100%|██████████████████| 7393/7393 [2:41:07<00:00,  1.31s/
Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|██████████| 313/313 [02:54<00:00,  1.80it/s]      
 all       5e+03    3.63e+04    0.000964    0.000638    5.18e-05    1.53e-05

**Comment by Syencil** [comment]
it is crucial to sparse learning

**Comment by eeric** [comment]
yolov5s.pt was pre-trained，then p, r and map@0.5 should not became smaller, while map@0.5 should be above 0.5 at least in the first few epoches.

**Comment by Syencil** [comment]
my pruning strategy is from [Learning Efficient Convolutional Networks through Network Slimming](https://arxiv.org/pdf/1708.06519.pdf). u can check the detail in paper. otherwise u can only try weight-level pruning. official repo have gave the answer [https://github.com/ultralytics/yolov5/issues/304](https://github.com/ultralytics/yolov5/issues/304). 
but weight-level pruning only achieve better fps in certain hard-ware or lib. its no way to prune the structure without sparse-learning in almost time.

**Comment by eeric** [comment]
oh, thanks!
I used sparse-learning, so no use prune.
